config/routes.rb
Rails.application.routes.draw do
  resources :communities
  devise_for :users
  resources :users
  get 'videos/search'
  resources :resources
  get 'home/index'
  root 'home#index'
  get 'home/support'
  post 'home/thank_you'
  get 'users/confirm'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :resources
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :confirm]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:index, :destroy]
  before_action :check_user, only: [:show]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @resources = Resource.where(user_id: current_user.id)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end



  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    @user.update(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Account is now up to date!' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = current_user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :alias, :password, :password_confirmation, :securecode, :user_key, :admin)
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :alias, :password, :password_confirmation, :securecode) }
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_verify.html.erb
<div class="popup">
  <div class="popup-header">
    <p>Verify Code</p>
  </div>
  <div class="popup-body">
      <%= form_for @user do |form| %>
        <%=form.label :user_key, "Enter moderator key:"%>
        <%=form.password_field :user_key, placeholder: "Enter the moderator key sent by email"%>
      <%=form.submit "Key", class:'btn btn-outline-custom my-sm-0'%>
    <%end%>
    <br>
    <br>
    <%=link_to "Close", "#", class: "btn btn-outline-custom my-sm-0", id: "dropdownclose"%>
  </div>
</div>

app/views/users/_verify_admin.html.erb
<div class="popup">
  <div class="popup-header">
    <p>Verify Code</p>
  </div>
  <div class="popup-body">
      <%= form_for @user do |form| %>
        <%=form.label :admin, "Enter admin key:"%>
        <%=form.password_field :admin, placeholder: "Enter the SECRET ADMIN KEY key sent by email"%>
      <%=form.submit "Key", class:'btn btn-outline-custom my-sm-0'%>
    <%end%>
    <br>
    <br>
    <%=link_to "Close", "#", class: "btn btn-outline-custom my-sm-0", id: "dropdownclose"%>
  </div>
</div>

app/views/users/_verify_moderator.html.erb
<div class="popup">
  <div class="popup-header">
    <p>Verify Code</p>
  </div>
  <div class="popup-body">
      <%= form_for @user do |form| %>
        <%=form.label :user_key, "Enter moderator key:"%>
        <%=form.password_field :user_key, placeholder: "Enter the moderator key sent by email"%>
      <%=form.submit "Key", class:'btn btn-outline-custom my-sm-0'%>
    <%end%>
    <br>
    <br>
    <%=link_to "Close", "#", class: "btn btn-outline-custom my-sm-0", id: "dropdownclose"%>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Alias</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.alias %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1 id="title">My Account</h1>
<hr>


<div class="row accountinformation">
  <div class="col-md-4 col-12">
    <p>
      First name:
      <%if @user.first_name.present?%>
      <p class="accountvariables"><%= @user.first_name %></p>
      <%end%>
    </p>
  </div>
  <div class="col-md-4 col-12">
    <p>
      Last name:
      <%if @user.last_name.present?%>
      <p class="accountvariables"><%= @user.last_name %></p>
      <%end%>
    </p>
  </div>
  <div class="col-md-4 col-12">
  <p>
    Alias:
    <%if @user.alias.present?%>
    <p class="accountvariables"><%= @user.alias %></p>
    <%end%>
  </p>
  </div>
  <div class="col-md-4 col-12">
  <p>
    Email:
    <p class="accountvariables"><%= @user.email %></p>
  </p>
  </div>
  <div class="col-md-4 col-12">
  <p>
    Moderator Status :
    <%if @user.user_key != @user.securecode%>
    <p class="accountvariables btn btn-outline-custom my-sm-0 verifybutton-moderator">Verify</p>
    <%end%>
    <%if @user.user_key == @user.securecode%>
    <p class="accountvariables verified">VERIFIED</p>
    <%end%>
  </p>
  </div>
  <div class="col-md-4 col-12">
  <p>
    Admin Status :
    <%if @user.admin.to_s != @user.admin_key.to_s%>
    <p class="accountvariables btn btn-outline-custom my-sm-0 verifybutton-admin">Verify</p>
    <%end%>
    <%if @user.admin.to_s == @user.admin_key.to_s%>
    <p class="accountvariables verified">VERIFIED</p>
    <%end%>
  </p>
  </div>
  <div class="col-md-4 col-12">
  <p>
    <%= link_to 'Edit Account Details', edit_user_path(@user), class: "btn btn-outline-custom my-sm-0"%>
    <%= link_to 'Back', users_path, class: "btn btn-outline-custom my-sm-0" %>
    <%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-custom my-sm-0" %>
  </p>
  </div>
</div>
<%if @user.user_key != @user.securecode%>
  <div class="warning verifybutton" >
    <p>You have not yet activated your account to become a moderator. If you do not wish to upload or contribute you do not need to activate your account. Click here if you wish to activate your account</p>
  </div>
<%else%>
  <div class="verified" >
    <p>You have now registered to be a moderator. You can submit content and help support the GMR page!!!</p>
  </div>
<%end%>
<br>

<div id="dropdown-moderator">
  <%=render "verify_moderator"%>
</div>


<div id="dropdown-admin">
  <%=render "verify_admin"%>
</div>


<br>
<h3>My Resources</h3>
<hr>
<div class="row tableheader">
  <div class="col-10 col-md-4">
    <p>Resource Name</p>
  </div>
  <div class="col-2 col-md-1">
    <p>Views</p>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('pdf_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('word_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('pp_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('qs_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('as_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('admin_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('cog_icon.png', class: 'tableicon')%>
  </div>
</div>

<%@resources.each do |resource|%>
<div class="row datarow">

  <div class="col-10 col-md-4">
    <%= link_to resource.name, resource %>
  </div>
  <div class="col-2 col-md-1">
    <p class="tick"><%=resource.views.to_s%></p>
  </div>
  <div class="col-1 pc-only">
    <%if resource.cs_pdf.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.cs_word.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.pp.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.question_sheet.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.answer_sheet.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <p class="tick">✓</p>
  </div>
  <div class="col-1 pc-only">
    <p class="tick"><%= link_to 'E', edit_resource_path(resource) %></p>
  </div>
</div>
<%end%>