config/routes.rb
Rails.application.routes.draw do
  resources :communities
  devise_for :users
  resources :users
  get 'videos/search'
  resources :resources
  get 'home/index'
  root 'home#index'
  get 'home/support'
  post 'home/thank_you'
  get 'users/confirm'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/community.rb
class Community < ApplicationRecord
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :set_community, only: [:show, :edit, :update, :destroy]

  # GET /communities
  # GET /communities.json
  def index
    @resources = Resource.where.not(user_id: "4").order(:created_at)
    if params[:q]
      search_term = params[:q]
      @resources = Resource.where("name LIKE ?", "%#{search_term}%").order(:created_at)
    end
    if params[:higher] && params[:higher] != "All"
      @resources = @resources.where(higher: params[:higher])
    end
    if (params[:topic] && params[:topic] != "All")
      @resources = @resources.where(topic: params[:topic])
    end
  end

  # GET /communities/1
  # GET /communities/1.json
  def show
    if params[:l]
      @horizontal = true
    end
    @creator = User.find(@resource.user_id)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_community
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def community_params
      params.require(:community).permit(:index)
    end
end

app/helpers/communities_helper.rb
module CommunitiesHelper
end

app/views/communities/_form.html.erb
<%= form_with(model: community, local: true) do |form| %>
  <% if community.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(community.errors.count, "error") %> prohibited this community from being saved:</h2>

      <ul>
      <% community.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :index %>
    <%= form.text_field :index %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/communities/edit.html.erb
<h1>Editing Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Show', @community %> |
<%= link_to 'Back', communities_path %>

app/views/communities/index.html.erb
<p id="notice"><%= notice %></p>

<h1 id="title">Watcha looking for?</h1>
<p id = "searchbarsubtitle">Search hundreds of maths resources all in one place in seconds... For FREE!</p>

<div class="container searchbar">
  <%= form_with(url: resources_path, method: 'get', local: true, class:'form-inline my-2 my-lg-0') do |form| %>
    <%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control mr-sm-2 searchfield'%>
    <%= form.select(:higher, Resource::SEARCHLEVEL_LIST) %>
    <%= form.select(:topic, Resource::SEARCHTOPIC_LIST)%>
    <%= form.submit 'Search', class: "btn btn-outline-custom my-sm-0",  type:"submit", role:"group" %>
  <%end%>
</div>


<div class="row tableheader">
  <div class="col-10 col-md-4">
    <p>Resource Name</p>
  </div>
  <div class="col-2 col-md-1">
    <p>Views</p>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('pdf_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('word_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('pp_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('qs_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('as_icon.png', class: 'tableicon')%>
  </div>
  <div class="col-1 pc-only">
    <%=image_tag('admin_icon.png', class: 'tableicon')%>
  </div>
  <%if user_signed_in?%>
    <%if current_user.admin == current_user.admin_key%>
      <div class="col-1 pc-only">
        <%=image_tag('cog_icon.png', class: 'tableicon')%>
      </div>
    <%end%>
  <%end%>
</div>

<%@resources.each do |resource|%>
<div class="row datarow">

  <div class="col-10 col-md-4">
    <%= link_to resource.name, resource %>
  </div>
  <div class="col-2 col-md-1">
    <p class="tick"><%=resource.views.to_s%></p>
  </div>
  <div class="col-1 pc-only">
    <%if resource.cs_pdf.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.cs_word.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.pp.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.question_sheet.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <%if resource.answer_sheet.attached?%>
      <p class="tick">✓</p>
    <%end%>
  </div>
  <div class="col-1 pc-only">
    <p class="tick">✓</p>
  </div>
  <%if user_signed_in?%>
    <%if current_user.admin == current_user.admin_key%>
      <div class="col-1 pc-only">
        <p class="tick"><%= link_to 'E', edit_resource_path(resource) %><%= link_to 'D', resource, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div>
    <%end%>
  <%end%>
</div>
<%end%>


<br>
<div class="admin">
  <%= link_to 'New Resource', new_resource_path, class: "btn btn-outline-custom" %>
</div>

app/views/communities/new.html.erb
<h1>New Community</h1>

<%= render 'form', community: @community %>

<%= link_to 'Back', communities_path %>

app/views/communities/show.html.erb
<%@resource.increment!(:views)%>
<%if params[:r]%>
  <%case params[:r]%>
  <%when "easy"%>
    <%@resource.increment!(:easy)%>
  <%when "hard"%>
    <%@resource.increment!(:hard)%>
  <%when "useful"%>
    <%@resource.increment!(:useful)%>
  <%end%>
<%end%>
<p id="notice"><%= notice %></p>
<h2 id="title"><%=@resource.name%></h2>
<hr>
<div class="row">
  <div class="col-12">
    <%=link_to "Back to topics", resources_path, class:"btn btn-outline-custom my-sm-0 navbuttons"%>
    <%= form_with(url: @resource, method: "get", local: true) do |form| %>
      <%=form.hidden_field :r, value: 'easy'%>
      <%=form.submit "Easy", class:'btn btn-outline-custom my-sm-0 navbuttons', id: "easy"%>
    <%end%>
    <%= form_with(url: @resource, method: "get", local: true) do |form| %>
      <%=form.hidden_field :r, value: 'hard'%>
      <%=form.submit "Hard", class:'btn btn-outline-custom my-sm-0 navbuttons', id: "hard"%>
    <%end%>
    <%= form_with(url: @resource, method: "get", local: true) do |form| %>
      <%=form.hidden_field :r, value: 'useful'%>
      <%=form.submit "Useful", class:' btn btn-outline-custom my-sm-0 navbuttons',id: "useful"%>
    <%end%>
  </div>
</div>
<br>
<br>


<div class="row">

  <%if @horizontal == true%>
  <div class="col-12">
    <style>.youtubevideo {width: 40%; display:inline-block; text-align: center;}
           .videos {text-align: center;}
    </style>
  <%else%>
  <div class="col-sm-6">
  <%end%>
    <h4>Useful Videos</h4>
    <hr>
    <div class="videos">
      <%if @resource.video_one.present?%>
        <iframe class="youtubevideo" src="<%=@resource.video_one%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <%end%>

      <%if @resource.video_two.present?%>
        <iframe class="youtubevideo" src="<%=@resource.video_two%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <%end%>
    </div>
  </div>
  <div class="col-sm-6 resourcelinkside">
    <h4>Resources</h4>

    <hr>

    <%if @resource.cs_pdf.attached?%>
      <div class="resourcebutton">
        <%=image_tag('pdf_icon.png', class:"type-icon")%>
        <%= link_to 'Cheatsheet PDF', rails_blob_path(@resource.cs_pdf), target: '_blank' %>
      </div>
      <br>
    <%end%>

    <%if @resource.cs_word.attached?%>
      <div class="resourcebutton">
        <%=image_tag('word_icon.png', class:"type-icon")%>
        <%= link_to 'Cheatsheet Word', rails_blob_path(@resource.cs_word, disposition: 'preview'), target: '_blank' %>
      </div>
      <br>
    <%end%>

    <%if @resource.pp.attached?%>
      <div class="resourcebutton">
        <%=image_tag('pp_icon.png', class:"type-icon")%>
        <%= link_to 'Download Powerpoint', rails_blob_path(@resource.pp, disposition: 'preview'), target: '_blank' %>
      </div>
      <br>
    <%end%>

    <%if @resource.question_sheet.attached?%>
      <div class="resourcebutton">
        <%=image_tag('pdf_icon.png', class:"type-icon")%>
        <%= link_to 'Questions', rails_blob_path(@resource.question_sheet, disposition: 'preview'), target: '_blank' %>
      </div>
      <br>
    <%end%>

    <%if @resource.answer_sheet.attached?%>
      <div class="resourcebutton">
        <%=image_tag('pdf_icon.png', class:"type-icon")%>
        <%= link_to 'Answers', rails_blob_path(@resource.answer_sheet, disposition: 'preview'), target: '_blank' %>
      </div>
      <br>
    <%end%>


  </div>
</div>


<br>
<h4>Resource Information</h4>
<hr>
<div class="row">
  <div class="col-sm-6">
    <p class="timestamps"><strong>Creator</strong>  - Louie Ormston</p>
    <p class="timestamps"><strong>Distribution</strong> - This is a free resource which can be shared and used freely</p>
    <p class="timestamps"><strong>Level</strong> - <%= @resource.higher%></p>
  </div>
  <div class="col-sm-6">
    <p class="timestamps"><strong>Date Of Creation</strong>  - <%=@resource.created_at%></p>
    <p class="timestamps"><strong>Last Updated</strong> - <%=@resource.updated_at%></p>
  </div>
</div>

<%= form_with(url: @resource, method: "get", local: true) do |form| %>
  <%=form.hidden_field :l, value: 'horizontal'%>
  <%=form.submit "Flip the switch", class:'layoutbutton btn btn-outline-custom my-sm-0'%>
<%end%>
<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>