config/routes.rb
Rails.application.routes.draw do
  resources :communities
  devise_for :users
  resources :users
  get 'videos/search'
  resources :resources
  get 'home/index'
  root 'home#index'
  get 'home/support'
  post 'home/thank_you'
  get 'users/confirm'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GCSE MATHS RESOURCES</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Heebo:800|Poppins:500" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light">
      <%= link_to image_tag('gmr logo.png', class: 'navbarlogo navbar-brand'), home_index_path%>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Homepage', home_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Resources', resources_path, class: 'nav-link'%>
          </li>
          <li class="nav-item">
              <%= link_to 'Video Search', videos_search_path, class: 'nav-link'%>
          </li>

          <li class="nav-item"><%=link_to "GMR Community", communities_path, class:"nav-link"%></li>
          <li class="nav-item">
            <%= link_to 'Support Us', home_support_path, class: 'nav-link'%>
          </li>
          <%if user_signed_in?%>
            <%=link_to 'My Account', current_user, class: 'nav-link'%>
          <%end%>
        </ul>

        <%= form_with(url: resources_path, method: 'get', local: true, class:'form-inline my-2 my-lg-0') do |form| %>
          <%= form.text_field :q, id: 'q', value: params[:q], class: 'form-control mr-sm-2'%>
          <%= form.submit 'Search', class: "btn btn-outline-custom my-sm-0",  type:"submit", role:"group" %>
        <%end%>
      </div>
    </nav>
    <br>

    <p class="notice"><%= notice %></p>

    <div class="backdrop">
      <div class="notnav">
        <%=yield%>
      </div>

    </div>
    <footer>
      <div class="row">
        <div class="col-6 col-sm-3"><%=link_to "Home", home_index_path%></div>
        <div class="col-6 col-sm-3"><%=link_to "Resources", resources_path%></div>
        <div class="col-6 col-sm-3"><%=link_to "Video Search", videos_search_path%></div>
        <div class="col-6 col-sm-3"><%=link_to "GMR Community", communities_path%></div>
        <% if user_signed_in?%>
          <div class="col-12"><%= link_to('LOGOUT', destroy_user_session_path, method: :delete) %></div>
        <% else%>
          <div class="col-12"><%=link_to('LOGIN', new_user_session_path) %></div>
        <%end%>
        <div class="col-12"><%=link_to "Designed and developed by Louie Ormston", "https://louie-ormston-portfolio.herokuapp.com/", target: "_blank"%></div>

    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
  </body>

</html>